// Dummy data for Stitchify application

export const dummyUsers = [
  {
    _id: 'user1',
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=250&q=80',
    role: 'user',
    favorites: ['design1', 'design3', 'design5'],
    purchases: ['design2', 'design4'],
  },
  {
    _id: 'user2',
    name: 'John Doe',
    email: 'john@example.com',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=250&q=80',
    role: 'admin',
    favorites: ['design2', 'design6'],
    purchases: ['design1', 'design3', 'design5'],
  },
  {
    _id: 'user3',
    name: 'Emily Johnson',
    email: 'emily@example.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=250&q=80',
    role: 'user',
    favorites: ['design4', 'design8'],
    purchases: ['design6', 'design7'],
  },
];

export const dummyCategories = [
  {
    _id: 'cat1',
    name: 'Floral',
    description: 'Beautiful floral patterns for any project',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { _id: 'subcat1', name: 'Roses', parentId: 'cat1' },
      { _id: 'subcat2', name: 'Wildflowers', parentId: 'cat1' },
      { _id: 'subcat3', name: 'Tropical', parentId: 'cat1' },
    ],
  },
  {
    _id: 'cat2',
    name: 'Animals',
    description: 'Adorable animal designs for children and adults alike',
    image: 'https://images.unsplash.com/photo-1484557985045-edf25e08da73?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { _id: 'subcat4', name: 'Pets', parentId: 'cat2' },
      { _id: 'subcat5', name: 'Wildlife', parentId: 'cat2' },
      { _id: 'subcat6', name: 'Farm Animals', parentId: 'cat2' },
    ],
  },
  {
    _id: 'cat3',
    name: 'Seasonal',
    description: 'Festive designs for holidays and special occasions',
    image: 'https://images.unsplash.com/photo-1543589923-d58654413866?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { _id: 'subcat7', name: 'Christmas', parentId: 'cat3' },
      { _id: 'subcat8', name: 'Halloween', parentId: 'cat3' },
      { _id: 'subcat9', name: 'Easter', parentId: 'cat3' },
    ],
  },
  {
    _id: 'cat4',
    name: 'Monograms',
    description: 'Personalized monogram designs for a special touch',
    image: 'https://images.unsplash.com/photo-1599032909756-5deb82fea3b0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { _id: 'subcat10', name: 'Classic', parentId: 'cat4' },
      { _id: 'subcat11', name: 'Modern', parentId: 'cat4' },
      { _id: 'subcat12', name: 'Ornate', parentId: 'cat4' },
    ],
  },
  {
    _id: 'cat5',
    name: 'Geometric',
    description: 'Clean, modern geometric patterns and designs',
    image: 'https://images.unsplash.com/photo-1565214975484-3cfa9e56f914?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { _id: 'subcat13', name: 'Abstract', parentId: 'cat5' },
      { _id: 'subcat14', name: 'Patterns', parentId: 'cat5' },
      { _id: 'subcat15', name: 'Mandalas', parentId: 'cat5' },
    ],
  },
  {
    _id: 'cat6',
    name: 'Quotes & Text',
    description: 'Inspirational quotes and decorative text designs',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80',
    subcategories: [
      { _id: 'subcat16', name: 'Inspirational', parentId: 'cat6' },
      { _id: 'subcat17', name: 'Funny', parentId: 'cat6' },
      { _id: 'subcat18', name: 'Decorative', parentId: 'cat6' },
    ],
  },
];

export const dummyDesigns = [
  {
    _id: 'design1',
    title: 'Elegant Rose Bouquet',
    description: 'A beautiful arrangement of roses with delicate leaves and stems. Perfect for linens, pillows, and decorative items.',
    price: 12.99,
    images: [
      { url: 'https://images.unsplash.com/photo-1548094990-c16ca90f1f0d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', alt: 'Rose embroidery design' },
    ],
    categories: [
      { _id: 'cat1', name: 'Floral', slug: 'floral' },
      { _id: 'subcat1', name: 'Roses', slug: 'roses' },
    ],
    difficulty: 'Intermediate',
    stitchCount: 8750,
    downloads: 342,
    rating: { average: 4.8, count: 56 },
    sales: 289,
    featured: true,
  },
  {
    _id: 'design2',
    title: 'Playful Puppy',
    description: 'An adorable puppy design that will bring joy to any project. Great for children\'s items, pet accessories, and more.',
    price: 9.99,
    images: [
      { url: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', alt: 'Puppy embroidery design' },
    ],
    categories: [
      { _id: 'cat2', name: 'Animals', slug: 'animals' },
      { _id: 'subcat4', name: 'Pets', slug: 'pets' },
    ],
    difficulty: 'Beginner',
    stitchCount: 6250,
    downloads: 421,
    rating: { average: 4.9, count: 78 },
    sales: 356,
    featured: true,
  },
  {
    _id: 'design3',
    title: 'Christmas Ornament Set',
    description: 'A collection of festive Christmas ornaments to decorate your holiday projects. Includes 5 different designs.',
    price: 14.99,
    images: [
      { url: 'https://images.unsplash.com/photo-1544650039-22886f9b6a1a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', alt: 'Christmas ornament embroidery designs' },
    ],
    categories: [
      { _id: 'cat3', name: 'Seasonal', slug: 'seasonal' },
      { _id: 'subcat7', name: 'Christmas', slug: 'christmas' },
    ],
    difficulty: 'Intermediate',
    stitchCount: 12500,
    downloads: 287,
    rating: { average: 4.7, count: 42 },
    sales: 215,
    featured: false,
  },
  {
    _id: 'design4',
    title: 'Classic Monogram Frame',
    description: 'An elegant frame for monograms with ornate details. Customize with any initial for a personalized touch.',
    price: 8.99,
    images: [
      { url: 'https://images.unsplash.com/photo-1605883705077-8d3d3cebe78c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', alt: 'Monogram frame embroidery design' },
    ],
    categories: [
      { _id: 'cat4', name: 'Monograms', slug: 'monograms' },
      { _id: 'subcat10', name: 'Classic', slug: 'classic' },
    ],
    difficulty: 'Beginner',
    stitchCount: 5200,
    downloads: 512,
    rating: { average: 4.6, count: 89 },
    sales: 478,
    featured: true,
  },
  {
    _id: 'design5',
    title: 'Geometric Mandala',
    description: 'A stunning geometric mandala with intricate details. Perfect for home decor, meditation pillows, and more.',
    price: 11.99,
    images: [
      { url: 'https://images.unsplash.com/photo-1577083552792-a0d461cb3256?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', alt: 'Geometric mandala embroidery design' },
    ],
    categories: [
      { _id: 'cat5', name: 'Geometric', slug: 'geometric' },
      { _id: 'subcat15', name: 'Mandalas', slug: 'mandalas' },
    ],
    difficulty: 'Advanced',
    stitchCount: 18750,
    downloads: 198,
    rating: { average: 4.9, count: 32 },
    sales: 167,
    featured: true,
  },
  {
    _id: 'design6',
    title: 'Inspirational Quote',
    description: 'An elegant design featuring the quote "Home is where the heart is" with decorative elements.',
    price: 7.99,
    images: [
      { url: 'https://images.unsplash.com/photo-1518176258769-f227c798150e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', alt: 'Inspirational quote embroidery design' },
    ],
    categories: [
      { _id: 'cat6', name: 'Quotes & Text', slug: 'quotes-text' },
      { _id: 'subcat16', name: 'Inspirational', slug: 'inspirational' },
    ],
    difficulty: 'Beginner',
    stitchCount: 4800,
    downloads: 387,
    rating: { average: 4.5, count: 65 },
    sales: 312,
    featured: false,
  },
  {
    _id: 'design7',
    title: 'Tropical Flower Set',
    description: 'A vibrant collection of tropical flowers including hibiscus, bird of paradise, and plumeria. Perfect for summer projects.',
    price: 15.99,
    images: [
      { url: 'https://images.unsplash.com/photo-1554631221-f9603e6808be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', alt: 'Tropical flower embroidery designs' },
    ],
    categories: [
      { _id: 'cat1', name: 'Floral', slug: 'floral' },
      { _id: 'subcat3', name: 'Tropical', slug: 'tropical' },
    ],
    difficulty: 'Intermediate',
    stitchCount: 14200,
    downloads: 245,
    rating: { average: 4.7, count: 38 },
    sales: 198,
    featured: true,
  },
  {
    _id: 'design8',
    title: 'Wildlife Collection',
    description: 'A set of detailed wildlife embroidery designs featuring deer, fox, owl, and rabbit. Great for nature-themed projects.',
    price: 16.99,
    images: [
      { url: 'https://images.unsplash.com/photo-1545852528-fa22f7fcd63e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', alt: 'Wildlife embroidery designs' },
    ],
    categories: [
      { _id: 'cat2', name: 'Animals', slug: 'animals' },
      { _id: 'subcat5', name: 'Wildlife', slug: 'wildlife' },
    ],
    difficulty: 'Advanced',
    stitchCount: 22500,
    downloads: 178,
    rating: { average: 4.8, count: 29 },
    sales: 145,
    featured: false,
  },
];